---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: partition-service
  namespace: osdu-azure
spec:
  releaseName: partition-service
  dependsOn:
  - name: default-service
    namespace: osdu-azure
  - name: osdu-istio
    namespace: istio-system
  interval: 5m0s
  timeout: 6m
  chart:
    spec:
      chart: ./charts/self-managed-service
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    remediation:
      retries: 3
  rollback:
    timeout: 5m
    disableWait: false
    disableHooks: false
    recreate: false
    force: true
    cleanupOnFail: true
  targetNamespace: osdu-azure
  values:
    podIdentity: osdu-identity
    replicaCount: 2
    ingress:
      issuer: letsencrypt-prod-dns
      enableKeyvaultCert: false
    service:
      type: ClusterIP
      port: 80
