---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: self-managed-base
  namespace: osdu-azure
spec:
  releaseName: self-managed-base
  dependsOn:
  - name: osdu-base
    namespace: default
  - name: istio-base
    namespace: istio-system
  chart:
    spec:
      chart: ./charts/self-managed-base
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  interval: 5m0s
  timeout: 6m
  install:
    remediation:
      retries: 3
  targetNamespace: osdu-azure
