---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-tool
  namespace: dev-sample
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 85c01aeb-2eef-4927-b9da-efbfc9e62fd5
      resourcegroup: osdu-self-cplcfjd-vl3a-rg
      identity: osdu-self-cplcfjd-vl3a-osdu-identity
      identity_id: b89d5c96-9d0c-466e-b53f-f0d1ffa78f8e
      keyvault: osdu-self-cplcfj-vl3a-kv
      appid: 03fea41e-ff0c-4444-ac77-dc88216d3161
