---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-tool
  namespace: dev-sample
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 85c01aeb-2eef-4927-b9da-efbfc9e62fd5
      resourcegroup: osdu-self-cplcccae-ebq6-rg
      identity: osdu-self-cplcccae-ebq6-osdu-identity
      identity_id: 06191e1c-afd6-4067-9704-b7ae95352b5e
      keyvault: osdu-self-cplccc-ebq6-kv
      appid: 03fea41e-ff0c-4444-ac77-dc88216d3161
