---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: env-tool
  namespace: dev-sample
spec:
  values:
    azure:
      tenant: 72f988bf-86f1-41af-91ab-2d7cd011db47
      subscription: 85c01aeb-2eef-4927-b9da-efbfc9e62fd5
      resourcegroup: osdu-self-cplcfeij-b7lk-rg
      identity: osdu-self-cplcfeij-b7lk-osdu-identity
      identity_id: c3663825-789c-470d-8268-feb6b29d8ae3
      keyvault: osdu-self-cplcfe-b7lk-kv
      appid: 03fea41e-ff0c-4444-ac77-dc88216d3161
