name: '5. Stamp Load'

on:
  workflow_dispatch:

env:
  CLI_VERSION: 2.30.0
  PARTITION_NAME: opendes

jobs:

  initialize-entitlements:
    name: Entitlements Load
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: actions/checkout@v2

      - name: Environment Settings
        uses: Azure/cli@1.0.4
        with:
          azcliversion: ${{ env.CLI_VERSION }}
          inlineScript: |
            GROUP=$(az group list --query "[?contains(name, 'cpl${{ secrets.RAND }}')].name" -otsv)
            ENV_VAULT=$(az keyvault list --resource-group $GROUP --query [].name -otsv)
            REGISTRY=$(az acr list -g $GROUP --query [0].loginServer -otsv)
            DP_GROUP=$(az group list --query "[?contains(name, 'dpl${{ secrets.RAND }}')].name" -otsv |grep -v MC)
            DNS_HOST=$(az network public-ip list --resource-group $DP_GROUP --query [].dnsSettings.fqdn -otsv)

            echo "GROUP=$GROUP" >> $GITHUB_ENV
            echo "ENV_VAULT=$ENV_VAULT" >> $GITHUB_ENV
            echo "REGISTRY=$REGISTRY" >> $GITHUB_ENV
            echo "DNS_HOST=$DNS_HOST" >> $GITHUB_ENV

      - name: Provision Tenant
        uses: Azure/cli@1.0.4
        with:
          azcliversion: ${{ env.CLI_VERSION }}
          inlineScript: |
            AZURE_TENANT_ID=$(az account show --query tenantId -otsv)
            AZURE_CLIENT_ID=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/app-dev-sp-username --query value -otsv)
            AZURE_CLIENT_SECRET=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/app-dev-sp-password --query value -otsv)
            AZURE_AD_APP_RESOURCE_ID=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/aad-client-id --query value -otsv)

            TOKEN=$(curl --request POST \
            --url https://login.microsoftonline.com/$AZURE_TENANT_ID/oauth2/token \
            --header 'content-type: application/x-www-form-urlencoded' \
            --header 'user-agent: vscode-restclient' \
            --data grant_type=client_credentials \
            --data client_id=$AZURE_CLIENT_ID \
            --data client_secret=$AZURE_CLIENT_SECRET \
            --data resource=$AZURE_AD_APP_RESOURCE_ID |jq -r ".access_token")

            curl --request POST \
            --url https://$DNS_HOST/api/entitlements/v2/tenant-provisioning \
            --header 'accept: application/json' \
            --header "authorization: Bearer $TOKEN" \
            --header 'data-partition-id: opendes' \
            --header 'user-agent: vscode-restclient'

  schema-load:
    name: Common Schema Load
    runs-on: ubuntu-latest
    needs: initialize-entitlements
    steps:
      - uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: actions/checkout@v2

      - name: Environment Settings
        uses: Azure/cli@1.0.4
        with:
          azcliversion: ${{ env.CLI_VERSION }}
          inlineScript: |
            GROUP=$(az group list --query "[?contains(name, 'cpl${{ secrets.RAND }}')].name" -otsv)
            ENV_VAULT=$(az keyvault list --resource-group $GROUP --query [].name -otsv)

            echo "GROUP=$GROUP" >> $GITHUB_ENV
            echo "ENV_VAULT=$ENV_VAULT" >> $GITHUB_ENV

      - name: Configure .env
        run: |
          DP_GROUP=$(az group list --query "[?contains(name, 'dpl${{ secrets.RAND }}')].name" -otsv |grep -v MC)

          cat > .env << EOF
          DATA_PARTITION=${{ env.PARTITION_NAME }}
          AZURE_TENANT_ID=$(az account show --query tenantId -otsv)
          AZURE_DNS_NAME=$(az network public-ip list --resource-group $DP_GROUP --query [].dnsSettings.fqdn -otsv)
          AZURE_AD_APP_RESOURCE_ID=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/aad-client-id --query value -otsv)
          AZURE_CLIENT_ID=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/app-dev-sp-username --query value -otsv)
          AZURE_CLIENT_SECRET=$(az keyvault secret show --id https://${ENV_VAULT}.vault.azure.net/secrets/app-dev-sp-password --query value -otsv)
          EOF

      - name: Load Common Schema
        run: docker run --env-file .env msosdu.azurecr.io/schema-load:0.9.0
